spring:
  datasource:
    url : jdbc:mysql://localhost:3306/hospatal
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : 1234
  data:
    redis:
      host : localhost
      port : 6379